#pragma once
// ============================================================
// Smart Virtual Fence System — Secrets
// DO NOT commit this file to version control!
// ============================================================

// SIM APN settings (change to your carrier)
#define GPRS_APN        "internet"   // e.g. "orange.tn", "ooredoo"
#define GPRS_USER       ""           // Leave empty if not required
#define GPRS_PASS       ""           // Leave empty if not required

// Backend JWT token (generated by backend for this device)
#define BEARER_TOKEN    "REPLACE_WITH_VALID_JWT_TOKEN"
